### ISSUE TITLE
Ignore deleted collections

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-process#264] opened 2020-02-26 14:58 UTC
When we create a new compile-releases collection with  `python ocdskingfisher-process-cli new-transform-compile-releases`, it would be helpful to ignore collections with deleted mark after `python ocdskingfisher-process-cli delete-collection`

**Comment by jpmckinney** [comment] 2020-02-26 15:45
I think this is a duplicate of #142. In the meantime, you should be able to re-create the collection once the old collection is completely deleted.

**Closed by jpmckinney** 2020-02-26 15:45 UTC
