### ISSUE TITLE
Compiled Releases Transform does not deal with different schema versions / extensions properly

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#11] opened 2019-01-11 11:56 UTC
Note you can pass a custom schema to OCDSMerge, we don't do this at all. 

We have access to any original release packages in the source data that exist while doing the transform, so we should be able to do something.

However, when calculating the compiled release from a series of releases: How do we calculate what the custom release schema should be if the schema version or extensions used or versions of extensions used changes half way through the series of releases?

**Comment by jpmckinney** [comment] 2019-01-11 14:46
Note that the [OCDS Kit compile command](https://github.com/open-contracting/ocdskit/blob/master/ocdskit/cli/commands/compile.py) determines which version of the release schema to use, and there's an open issue to merge extensions' schema https://github.com/open-contracting/ocdskit/issues/85

Regarding changes in extensions used: This shouldn't affect the results of merging, unless extensions change each other's field definitions, which isn't allowed and might never occur in reality.

Regarding changes in versions of OCDS or extensions:

1. This might not ever happen in reality, so we can at least start with the assumption that all packages use the same versions of OCDS and extensions
1. If the OCDS version changes, the behavior of OCDS Kit is to error, and to prompt the user to upgrade all the data to the same version (and supplies the command to do so). OCDS Kit's upgrade behavior is to upgrade any package matching the old version, and to pass-through everything else; that way, we don't try to upgrade data that's already been upgraded.
1. If extensions' versions change, I figure the latest version in use should be preferred, as it's most likely to include any bug fixes with respect to merging behavior.

There are still edge cases to the above, but I don't think there is anyway to resolve them without abandoning the merge entirely.

**Comment by jpmckinney** [comment] 2019-12-10 01:33
Related: #122

**Comment by jpmckinney** [comment] 2020-01-09 16:18
I think the Sentry errors https://sentry.io/organizations/open-data-services/issues/1425503400/?project=1404981&query=is%3Aunresolved and https://sentry.io/organizations/open-data-services/issues/1400269463/?project=1404981&query=is%3Aunresolved are related (OCDS Merge isn't given the merge rules for the bids extension), but OCDS Merge should also be updated to tolerate this input.

**Comment by jpmckinney** [comment] 2020-01-09 16:50
I tried to reproduce with the same version of OCDS Merge, using the `release` from the `ocdsmerge/merge.py in _create_merged_release at line 429` step in Sentry, but it didn't error. I think Sentry isn't reporting the actual release that causes the issue (the releases through the stacktrace are inconsistent). For posterity (since it required a little cleanup), here's the release I used.

```json
{
  "awards": [
    {
      "hasSubcontracting": true,
      "status": "active",
      "subcontracting": {
        "description": "0"
      },
      "suppliers": [
        {
          "id": 4,
          "name": "1One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred One hundred"
        }
      ]
    }
  ],
  "bids": {
    "statistics": [
      {
        "id": "1",
        "measure": "bids",
        "value": "2"
      },
      {
        "id": "2",
        "measure": "smeBids",
        "value": "1"
      },
      {
        "id": "3",
        "measure": "foreignBidsFromEU",
        "value": "1"
      },
      {
        "id": "4",
        "measure": "lowestValidBidValue",
        "value": {
          "amount": 40,
          "currency": "GBP"
        }
      },
      {
        "id": "5",
        "measure": "highestValidBidValue",
        "value": {
          "amount": 40,
          "currency": "GBP"
        }
      }
    ]
  },
  "buyer": {
    "id": 1,
    "name": "Crown Commercial Service"
  },
  "date": "2018-12-21T15:28:35Z",
  "id": null,
  "ocid": null,
  "parties": [
    {
      "address": {
        "countryName": "United Kingdom",
        "locality": "Norwich",
        "postalCode": "NR70HS",
        "region": "UKI32",
        "streetAddress": "Rosebery Court, 2 Central Ave"
      },
      "contactPoint": {
        "email": "erik.upton@crowncommercial.gov.uk",
        "name": "Erik Upton",
        "telephone": "+44 1234567890"
      },
      "id": 1,
      "identifier": {
        "legalName": "Crown Commercial Service"
      },
      "name": "Crown Commercial Service",
      "roles": [
        "buyer"
      ]
    },
    {
      "id": 9999999,
      "name": "European Union",
      "roles": [
        "funder"
      ]
    },
    {
      "address": {
        "countryName": "United Kingdom",
        "locality": "dfkl;j",
        "postalCode": "W1A 1AA",
        "region": "UKI32",
        "streetAddress": "hdfjl"
      },
      "contactPoint": {
        "email": "a@b.co.uk"
      },
      "details": {
        "scale": "sme"
      },
      "id": 4,
      "identifier": {
        "id": "One hundred One hundred One h",
        "legalName": "1One hundred One hundred One hundred ..."
      }
    }
  ]
}
```

**Comment by jpmckinney** [comment] 2020-04-16 19:39
Noting that OCDS Kit has [ocdskit.combine.merge](https://ocdskit.readthedocs.io/en/latest/api/combine.html#ocdskit.combine.merge) and OCDS Merge has [documentation](https://ocds-merge.readthedocs.io/en/latest/create-merged-releases.html#patch-the-schema) for merging using extended schema.

**Comment by jpmckinney** [comment] 2020-08-13 19:32
OCDS Kit's merge method does this now for free, so it will be used in the Django branch instead of using OCDS Merge directly. #122 is still open, as we should calculate and store the patched schema once the collection is complete, to guarantee we have the versions of extensions from the time of collection.

**Closed by jpmckinney** 2020-08-13 19:32 UTC
Labels: transform
